
project:
  type: website
  output-dir: docs

execute:
  freeze: auto

format:
  html:
    theme: assets/css/theme-stern.scss
    css: assets/css/styles.css
    toc: false
    mainfont: "Source Serif 4"
    monofont: "Source Code Pro"

website:
  navbar:
      pinned: TRUE
      search: TRUE
      collapse: false
      right:
        - text: "<b>Menu</b>"
          menu:
            - icon: house-door-fill
              text: "Home"
              href: index.html
            - icon: card-text
              text: "About / CV"
              href: about.html
            - icon: bar-chart-fill
              text: "Data Collection and Production"
              href: data-collection.html
            - icon: cpu-fill
              text: "EPPS 6323: Knowledge Mining"
              href: knowledge_mining.html
            - icon: database-fill
              text: "EPPS 6354: Information Management"
              href: info_management.html
            - icon: github
              text: "Github"
              href: "https://github.com/EmilyRStern/"
            - icon: linkedin
              text: "Linkedin"
              href: "https://www.linkedin.com/in/emily-stern-83479b154/"
